id = "monospace-theme"
name = "Monospace Theme"
schema_version = 1
version = "0.1.1"
authors = ["Abhinav <itsabhinav5383@gmail.com>"]
description = "IDX Monospace theme for zed"
repository = "https://github.com/Abhinav5383/zed-monospace-theme"