import { DarkTheme, LightTheme, type ThemeColors } from "./palette";

const JSON_SCHEMA_URL = "https://zed.dev/schema/themes/v0.2.0.json";

function generateTheme(colors: ThemeColors) {
	return {
		border: colors.border,
		"border.variant": colors.border_variant,
		"border.focused": colors.border_focused,
		"border.selected": colors.border_variant,
		"border.transparent": "#00000000",
		"border.disabled": colors.border,
		"elevated_surface.background": colors.bg_panel,
		"surface.background": colors.bg_panel,
		background: colors.bg_panel,
		"element.background": colors.bg_panel_active,
		"element.hover": colors.bg_panel_hover,
		"element.active": colors.bg_panel_active,
		"element.selected": colors.bg_panel_selected,
		"element.disabled": colors.bg_panel,
		"drop_target.background": colors.bg_drop_target,
		"ghost_element.background": "#00000000",
		"ghost_element.hover": colors.bg_panel_hover,
		"ghost_element.active": colors.bg_panel_active,
		"ghost_element.selected": colors.bg_panel_selected,
		"ghost_element.disabled": colors.bg_panel,
		text: colors.text,
		"text.muted": colors.text_muted,
		"text.placeholder": colors.text_disabled,
		"text.disabled": colors.text_disabled,
		"text.accent": colors.text_accent,
		icon: colors.text,
		"icon.muted": colors.text_muted,
		"icon.disabled": colors.text_disabled,
		"icon.placeholder": colors.text_muted,
		"icon.accent": colors.text_accent,
		"status_bar.background": colors.bg_panel,
		"title_bar.background": colors.bg_panel,
		"title_bar.inactive_background": colors.bg_panel,
		"toolbar.background": colors.bg_main,
		"tab_bar.background": colors.bg_panel,
		"tab.inactive_background": colors.bg_panel,
		"tab.active_background": colors.bg_main,
		"search.match_background": colors.bg_search_match,
		"panel.background": colors.bg_panel,
		"panel.focused_border": colors.border_focused,
		"pane.focused_border": null,
		"scrollbar.thumb.background": colors.scroll_thumb_bg,
		"scrollbar.thumb.hover_background": colors.scroll_thumb_bg_hover,
		"scrollbar.thumb.border":
			colors.scroll_thumb_border || colors.border_variant,
		"scrollbar.track.background": colors.scroll_track_bg || "#00000000",
		"scrollbar.track.border": colors.scroll_track_border,
		"panel.indent_guide": colors.panel_indent,
		"panel.indent_guide_active": colors.panel_indent_active,
		"editor.indent_guide": colors.editor_indent,
		"editor.indent_guide_active": colors.editor_indent_active,
		"editor.foreground": colors.editor_foreground,
		"editor.background": colors.bg_main,
		"editor.gutter.background": colors.bg_main,
		"editor.subheader.background": colors.bg_panel,
		"editor.active_line.background": colors.editor_active_line_bg,
		// "editor.highlighted_line.background": colors.bg_main, // For some reason it doesn't work
		"editor.line_number": colors.editor_line_number_fg,
		"editor.active_line_number": colors.editor_line_number_fg_active,
		// "editor.hover_line_number": null, // wtf is this?
		"editor.invisible": colors.text_disabled,
		// "editor.wrap_guide": "#c8ccd40d", // no idea what it does
		// "editor.active_wrap_guide": "#c8ccd41a",
		"editor.document_highlight.read_background": colors.editor_similar_token_bg,
		"editor.document_highlight.bracket_background":
			colors.editor_wrapping_brackets_bg,
		// "editor.document_highlight.write_background": "#555a6366",

		"terminal.background": colors.terminal.background,
		"terminal.foreground": colors.terminal.foreground,
		// "terminal.bright_foreground": colors.terminal.bright_foreground,
		// "terminal.dim_foreground": colors.terminal.dim_foreground,
		// "terminal.ansi.black": colors.terminal.black,
		// "terminal.ansi.bright_black": colors.terminal.bright_black,
		// "terminal.ansi.dim_black": colors.terminal.dim_black,
		// "terminal.ansi.red": colors.terminal.red,
		// "terminal.ansi.bright_red": colors.terminal.bright_red,
		// "terminal.ansi.dim_red": colors.terminal.dim_red,
		// "terminal.ansi.green": colors.terminal.green,
		// "terminal.ansi.bright_green": colors.terminal.bright_green,
		// "terminal.ansi.dim_green": colors.terminal.dim_green,
		// "terminal.ansi.yellow": colors.terminal.yellow,
		// "terminal.ansi.bright_yellow": colors.terminal.bright_yellow,
		// "terminal.ansi.dim_yellow": colors.terminal.dim_yellow,
		// "terminal.ansi.blue": colors.terminal.blue,
		// "terminal.ansi.bright_blue": colors.terminal.bright_blue,
		// "terminal.ansi.dim_blue": colors.terminal.dim_blue,
		// "terminal.ansi.magenta": colors.terminal.magenta,
		// "terminal.ansi.bright_magenta": colors.terminal.bright_magenta,
		// "terminal.ansi.dim_magenta": colors.terminal.dim_magenta,
		// "terminal.ansi.cyan": colors.terminal.cyan,
		// "terminal.ansi.bright_cyan": colors.terminal.bright_cyan,
		// "terminal.ansi.dim_cyan": colors.terminal.dim_cyan,
		// "terminal.ansi.white": colors.terminal.white,
		// "terminal.ansi.bright_white": colors.terminal.bright_white,
		// "terminal.ansi.dim_white": colors.terminal.dim_white,

		"link_text.hover": colors.text_accent,
		"version_control.added": colors.vcs_added_bg,
		"version_control.modified": colors.vcs_modified_bg,
		"version_control.deleted": colors.vcs_deleted_bg,

		conflict: colors.conflict_fg,
		"conflict.background": colors.bg_panel,
		"conflict.border": colors.border,
		created: colors.created_fg,
		"created.background": colors.bg_panel,
		"created.border": colors.border,
		deleted: colors.deleted_fg,
		"deleted.background": colors.bg_panel,
		"deleted.border": colors.border,
		error: colors.error_fg,
		"error.background": colors.bg_panel,
		"error.border": colors.border,
		hidden: colors.hidden_fg,
		"hidden.background": colors.bg_panel,
		"hidden.border": colors.border,
		hint: colors.hint_fg,
		"hint.background": colors.bg_panel,
		"hint.border": colors.border,
		ignored: colors.ignored_fg,
		"ignored.background": colors.bg_panel,
		"ignored.border": colors.border,
		info: colors.info_fg,
		"info.background": colors.bg_panel,
		"info.border": colors.border,
		modified: colors.modified_fg,
		"modified.background": colors.bg_panel,
		"modified.border": colors.border,
		predictive: colors.predictive_fg,
		"predictive.background": colors.bg_panel,
		"predictive.border": colors.border,
		renamed: colors.renamed_fg,
		"renamed.background": colors.bg_panel,
		"renamed.border": colors.border,
		success: colors.success_fg,
		"success.background": colors.bg_panel,
		"success.border": colors.border,
		unreachable: colors.unreachable_fg,
		"unreachable.background": colors.bg_panel,
		"unreachable.border": colors.border,
		warning: colors.warning_fg,
		"warning.background": colors.bg_panel,
		"warning.border": colors.border,

		players: colors.players,
		syntax: {
			variable: {
				color: colors.syntax.white,
				font_style: null,
				font_weight: null,
			},
			"variable.builtin": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"variable.parameter": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"variable.member": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"variable.special": {
				color: colors.syntax.yellow,
				font_style: null,
				font_weight: null,
			},
			constant: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"constant.builtin": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"constant.macro": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			module: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			label: {
				color: colors.syntax.sky,
				font_style: null,
				font_weight: null,
			},
			string: {
				color: colors.syntax.green,
				font_style: null,
				font_weight: null,
			},
			"string.documentation": {
				color: colors.syntax.light_green,
				font_style: null,
				font_weight: null,
			},
			"string.regexp": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"string.escape": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"string.special": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"string.special.path": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"string.special.symbol": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"string.special.url": {
				color: colors.syntax.brown,
				font_style: null,
				font_weight: null,
			},
			character: {
				color: colors.syntax.light_green,
				font_style: null,
				font_weight: null,
			},
			"character.special": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			boolean: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			number: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"number.float": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			type: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"type.builtin": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"type.definition": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"type.interface": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"type.super": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			attribute: {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			property: {
				color: colors.syntax.sky,
				font_style: null,
				font_weight: null,
			},
			function: {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			"function.builtin": {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			"function.call": {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			"function.macro": {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			"function.method": {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			"function.method.call": {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			constructor: {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			operator: {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			keyword: {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.modifier": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.type": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"keyword.coroutine": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.function": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.operator": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.import": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.repeat": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.return": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.debug": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.exception": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.conditional": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.conditional.ternary": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"keyword.directive": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"keyword.directive.define": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"keyword.export": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			punctuation: {
				color: colors.syntax.muted_grey,
				font_style: null,
				font_weight: null,
			},
			"punctuation.delimiter": {
				color: colors.editor_foreground,
				font_style: null,
				font_weight: null,
			},
			"punctuation.bracket": {
				color: colors.syntax.muted_grey,
				font_style: null,
				font_weight: null,
			},
			"punctuation.special": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"punctuation.special.symbol": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"punctuation.list_marker": {
				color: colors.syntax.light_green,
				font_style: null,
				font_weight: null,
			},
			comment: {
				color: colors.syntax.muted_grey,
				font_style: null,
				font_weight: null,
			},
			"comment.doc": {
				color: colors.syntax.muted_grey,
				font_style: null,
				font_weight: null,
			},
			"comment.documentation": {
				color: colors.syntax.muted_grey,
				font_style: null,
				font_weight: null,
			},
			"comment.error": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"comment.warning": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"comment.hint": {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			"comment.todo": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"comment.note": {
				color: colors.syntax.brown,
				font_style: null,
				font_weight: null,
			},
			"diff.plus": {
				color: colors.syntax.green,
				font_style: null,
				font_weight: null,
			},
			"diff.minus": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			tag: {
				color: colors.syntax.green,
				font_style: null,
				font_weight: null,
			},
			"tag.attribute": {
				color: colors.syntax.green,
				font_style: null,
				font_weight: null,
			},
			"tag.delimiter": {
				color: colors.syntax.light_green,
				font_style: null,
				font_weight: null,
			},
			parameter: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			field: {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			namespace: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			float: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			symbol: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"string.regex": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			text: {
				color: colors.editor_foreground,
				font_style: null,
				font_weight: null,
			},
			"emphasis.strong": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: 700,
			},
			emphasis: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			embedded: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"text.literal": {
				color: colors.syntax.green,
				font_style: null,
				font_weight: null,
			},
			concept: {
				color: colors.syntax.sky,
				font_style: null,
				font_weight: null,
			},
			enum: {
				color: colors.syntax.light_green,
				font_style: null,
				font_weight: 700,
			},
			"function.decorator": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"type.class.definition": {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: 700,
			},
			hint: {
				color: colors.syntax.very_muted_grey,
				font_style: null,
				font_weight: null,
			},
			link_text: {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			link_uri: {
				color: colors.syntax.purple,
				font_style: null,
				font_weight: null,
			},
			parent: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			predictive: {
				color: colors.syntax.very_muted_grey,
				font_style: null,
				font_weight: null,
			},
			predoc: {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			primary: {
				color: colors.syntax.blue,
				font_style: null,
				font_weight: null,
			},
			"tag.doctype": {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
			"string.doc": {
				color: colors.syntax.muted_grey,
				font_style: null,
				font_weight: null,
			},
			title: {
				color: colors.editor_foreground,
				font_style: null,
				font_weight: 800,
			},
			variant: {
				color: colors.syntax.red,
				font_style: null,
				font_weight: null,
			},
		},
	};
}

const theme = {
	$schema: JSON_SCHEMA_URL,
	name: "Monospace Theme",
	author: "Abhinav5383",
	themes: [
		{
			name: "Monospace dark",
			appearance: "dark",
			style: generateTheme(DarkTheme),
		},
		{
			name: "Monospace light",
			appearance: "light",
			style: generateTheme(LightTheme),
		},
	],
};

// @ts-expect-error
await Bun.file("./themes/monospace.json").write(JSON.stringify(theme, null, 4));
